### ISSUE TITLE
Doesn't works in Docker

### ISSUE THREAD

**Issue by xaviplazas** [fdegier/homebridge-somfy-hotwired#20]
Hi, I'm using the last homebridge image for Docker and it doesn't works. I had another SD card with homebridge installed in host mode and there it works fine but when I use the Docker image, it doesn't works.

The plugin is installed without problems, and it feel works fine, in the plugin appears the slide bar, you move the bar to some percentage and nothing moves. In te log, appears the message: "Operation completed!" but nothing.

I thing about some GPIO's permissions but I'm running Docker in Privilege Mode, I've mounted the /sys/ and /sys/class/gpio volumes, and even I created the /dev/gpiochip0 device.

Can comeoune help me?

**Comment by fdegier** [comment]
Hello, I also run it in Docker, here's my compose

```
version: '2'
services:
  homebridge:
    image: homebridge/homebridge:ubuntu
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - ./config:/homebridge
    environment:
      - PGID=0
      - PUID=0
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8090
   ```

I think you need to ensure your host has GPIO packages installed, do other packages work with GPIO? Perhaps try installing `wiringpi`
